#!/usr/bin/env python3
"""
Phase 2 (revised): Align highlight clips back to the original stream.

PRIMARY method  (when highlight .srt exists):
  Sliding-window 3-gram text matching between stream SRT and highlight SRT.
  Both were auto-generated by YouTube ASR on the same audio → text is nearly
  identical for the same speech, giving very precise alignment.

FALLBACK method (gura-solo-minecraft0 highlight has no SRT):
  Onset-strength cross-correlation via librosa.
  Uses the spectral onset envelope rather than raw RMS, which is much less
  affected by looping BGM music.

Algorithm:
  1. Parse + deduplicate both SRTs (YouTube rolling-word format).
  2. Build a 3-gram → [(stream_time, stream_sentence_idx)] inverted index.
  3. Slide a 30-second window (hop=5s) over the highlight.
     For each window extract its 3-grams, vote on stream positions.
  4. The highest-voted stream position = match for that window.
     Confidence = vote_count / total_3grams.
  5. Group consecutive windows with consistent offsets into segments.

Outputs per stream:
  research/<stream>/<stream>_alignment.csv
    highlight_file, segment_idx,
    highlight_start_s, highlight_end_s,
    stream_start_s,   stream_end_s,
    duration_s, mean_confidence, n_windows, method
"""

import argparse
import sys
import time
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from chatfreq.core.subtitle_processor import (
    parse_srt, deduplicate_rolling_cues, _clean_text
)
from chatfreq.core.time_utils import seconds_to_hms

SAMPLES_DIR  = PROJECT_ROOT / "samples"
RESEARCH_DIR = Path(__file__).resolve().parent

# ── Parameters ────────────────────────────────────────────────────────────────
WINDOW_SEC     = 30       # length of each alignment window (seconds)
HOP_SEC        = 5        # hop between windows (seconds)
NGRAM_N        = 3        # n-gram order for text matching
MIN_CONFIDENCE = 0.05     # minimum vote fraction to accept a window
OFFSET_TOL     = 45       # seconds – max offset drift within one segment
MIN_SEG_WIN    = 2        # minimum windows to form a segment
# Audio fallback (onset strength)
AUDIO_SR       = 8000
CORR_THRESHOLD = 0.20   # onset NCC threshold (lower than raw RMS – onset is less peaky)

# ── Stream manifest ───────────────────────────────────────────────────────────
STREAMS = {
    "gura-first-minecraft": {
        "stream_video": SAMPLES_DIR / "gura-first-minecraft" / "[MINECRAFT] BUILD ATLANTIS #GAWRGURA #HololiveEnglish [OlJQItn5Z2o].mkv",
        "stream_srt": SAMPLES_DIR / "gura-first-minecraft" / "[MINECRAFT] BUILD ATLANTIS #GAWRGURA #HololiveEnglish [OlJQItn5Z2o].en.srt",
        "highlights": [
            {
                "video": SAMPLES_DIR / "gura-first-minecraft" / "highlights" / "Gawr Gura Begins her MINECRAFT Journey! Best Moments! - Hololive EN Highlights [kwoZkGGZlv4].mkv",
                "srt":   SAMPLES_DIR / "gura-first-minecraft" / "highlights" / "Gawr Gura Begins her MINECRAFT Journey! Best Moments! - Hololive EN Highlights [kwoZkGGZlv4].en.srt",
            },
            {
                "video": SAMPLES_DIR / "gura-first-minecraft" / "highlights" / "Gawr Gura Builds Atlantis - First stream highlights 【HoloEN】【Minecraft】 [ZS6xn7fWIHQ].mkv",
                "srt":   SAMPLES_DIR / "gura-first-minecraft" / "highlights" / "Gawr Gura Builds Atlantis - First stream highlights 【HoloEN】【Minecraft】 [ZS6xn7fWIHQ].en.srt",
            },
            {
                "video": SAMPLES_DIR / "gura-first-minecraft" / "highlights" / "Gura's First Minecraft Stream ｜ Highlights [DHSnBVGTVes].mkv",
                "srt":   SAMPLES_DIR / "gura-first-minecraft" / "highlights" / "Gura's First Minecraft Stream ｜ Highlights [DHSnBVGTVes].en.srt",
            },
        ],
    },
    "gura-solo-minecraft0": {
        "stream_video": SAMPLES_DIR / "gura-solo-minecraft0" / "[MINECRAFT] I Want A Trident!!! [tQcV9eEH7fk].mkv",
        "stream_srt": SAMPLES_DIR / "gura-solo-minecraft0" / "[MINECRAFT] I Want A Trident!!! [tQcV9eEH7fk].en.srt",
        "highlights": [
            {
                "video": SAMPLES_DIR / "gura-solo-minecraft0" / "highlights" / "HololiveEN Gura's 10th solo Minecraft Highlights [MVykDx60kUE].mkv",
                "srt": None,  # no SRT → audio fallback
            },
        ],
    },
    "nimi-retro-rewind": {
        "stream_video": SAMPLES_DIR / "nimi-retro-rewind" / "【Retro Rewind】 Legally distinct Blockbuster simulator [7Px9qClCzt8].mkv",
        "stream_srt": SAMPLES_DIR / "nimi-retro-rewind" / "【Retro Rewind】 Legally distinct Blockbuster simulator [7Px9qClCzt8].en.srt",
        "highlights": [
            {
                "video": SAMPLES_DIR / "nimi-retro-rewind" / "highlights" / "Nimi Island Gets a New Resident and It\u2019s Nimi\u2019s Daughter [Bwmg1cpkUGk].mkv",
                "srt":   SAMPLES_DIR / "nimi-retro-rewind" / "highlights" / "Nimi Island Gets a New Resident and It\u2019s Nimi\u2019s Daughter [Bwmg1cpkUGk].en.srt",
            },
            {
                "video": SAMPLES_DIR / "nimi-retro-rewind" / "highlights" / "Nimi Opened a New Store and She Couldn\u2019t Stop Yapping [sCKzzi9HkNg].mkv",
                "srt":   SAMPLES_DIR / "nimi-retro-rewind" / "highlights" / "Nimi Opened a New Store and She Couldn\u2019t Stop Yapping [sCKzzi9HkNg].en.srt",
            },
        ],
    },
    "nimi-vampire": {
        "stream_video": SAMPLES_DIR / "nimi-vampire" / "【Vampire： The Masquerade - Bloodlines】 Living out my sick and twisted vampire dreams [Db54iFFWLWc].mkv",
        "stream_srt": SAMPLES_DIR / "nimi-vampire" / "【Vampire： The Masquerade - Bloodlines】 Living out my sick and twisted vampire dreams [Db54iFFWLWc].en.srt",
        "highlights": [
            {
                "video": SAMPLES_DIR / "nimi-vampire" / "highlights" / "Nimi gets scammed by a lady of the night, commits a crime, dies then dances (Vampire：The Masquerade) [I-xB_W1pl0Q].mkv",
                "srt":   SAMPLES_DIR / "nimi-vampire" / "highlights" / "Nimi gets scammed by a lady of the night, commits a crime, dies then dances (Vampire：The Masquerade) [I-xB_W1pl0Q].en.srt",
            },
            {
                "video": SAMPLES_DIR / "nimi-vampire" / "highlights" / "Nimi Hilariously Caused Havoc After Turning Into a Vampire [K0LAOOsc61g].mkv",
                "srt":   SAMPLES_DIR / "nimi-vampire" / "highlights" / "Nimi Hilariously Caused Havoc After Turning Into a Vampire [K0LAOOsc61g].en.srt",
            },
        ],
    },
}

# ── Text helpers ──────────────────────────────────────────────────────────────

def normalise_word(w: str) -> str:
    """Lowercase + strip punctuation for robust n-gram matching."""
    import re
    return re.sub(r"[^a-z0-9']", "", w.lower())


def tokenize(text: str) -> list[str]:
    words = [normalise_word(w) for w in text.split()]
    return [w for w in words if len(w) > 1]   # skip single punctuation chars


def get_ngrams(tokens: list[str], n: int) -> list[tuple]:
    return [tuple(tokens[i:i+n]) for i in range(len(tokens) - n + 1)]


def srt_to_timed_words(srt_path: Path) -> list[tuple[float, float, str]]:
    """
    Parse + deduplicate rolling SRT → list of (start_s, end_s, text) chunks.
    Filters out music/sound-effect-only cues and very short silences.
    """
    import re
    cues = parse_srt(str(srt_path))
    chunks = deduplicate_rolling_cues(cues)
    # Filter out music/sfx-only cues
    clean = []
    for (start, end, text) in chunks:
        t = _clean_text(text)
        # Skip cues that are purely music/sfx markers
        if re.match(r"^\[.*\]$", t) or re.match(r"^♪.*♪$", t):
            continue
        if len(tokenize(t)) >= 2:
            clean.append((start, end, t))
    return clean


# ── Subtitle alignment ────────────────────────────────────────────────────────

def build_stream_ngram_index(
    chunks: list[tuple[float, float, str]],
    n: int = NGRAM_N,
) -> dict[tuple, list[tuple[float, int]]]:
    """
    Build inverted index: ngram → list of (chunk_start_seconds, chunk_idx).
    """
    index: dict[tuple, list[tuple[float, int]]] = defaultdict(list)
    for idx, (start, end, text) in enumerate(chunks):
        tokens = tokenize(text)
        for ng in get_ngrams(tokens, n):
            index[ng].append((start, idx))
    return index


def get_chunks_in_window(
    chunks: list[tuple[float, float, str]],
    t_start: float,
    t_end: float,
) -> str:
    """Collect all text from chunks that overlap [t_start, t_end]."""
    parts = []
    for (cs, ce, text) in chunks:
        if ce <= t_start:
            continue
        if cs >= t_end:
            break
        parts.append(text)
    return " ".join(parts)


def vote_stream_position(
    highlight_window_text: str,
    stream_index: dict,
    stream_chunks: list,
    stream_duration_s: float,
    n: int = NGRAM_N,
    bin_size_s: float = 10.0,
) -> tuple[float | None, float]:
    """
    For a window of highlight text, vote on the best matching stream position.

    Returns (best_stream_start_s, confidence) where confidence = peak_votes / total_ngrams.
    """
    tokens = tokenize(highlight_window_text)
    ngrams = get_ngrams(tokens, n)
    if not ngrams:
        return None, 0.0

    # Vote into bins: each stream n-gram match votes for its stream_time bin
    n_bins = max(1, int(stream_duration_s / bin_size_s) + 1)
    votes = np.zeros(n_bins, dtype=np.int32)

    for ng in ngrams:
        if ng in stream_index:
            for (s_time, _) in stream_index[ng]:
                bin_idx = min(int(s_time / bin_size_s), n_bins - 1)
                votes[bin_idx] += 1

    peak_bin = int(np.argmax(votes))
    peak_votes = int(votes[peak_bin])
    confidence = peak_votes / len(ngrams)

    # Refine: find the earliest chunk in that bin range
    best_time = peak_bin * bin_size_s
    # find the actual chunk start closest to bin center
    bin_start = peak_bin * bin_size_s
    bin_end = bin_start + bin_size_s
    best_chunk_time = None
    best_chunk_votes = 0
    # Re-vote at chunk resolution within the winning bin
    chunk_votes: dict[int, int] = defaultdict(int)
    for ng in ngrams:
        if ng in stream_index:
            for (s_time, cidx) in stream_index[ng]:
                if bin_start - 5 <= s_time <= bin_end + 5:
                    chunk_votes[cidx] += 1
    if chunk_votes:
        best_cidx = max(chunk_votes, key=chunk_votes.get)
        best_chunk_time = stream_chunks[best_cidx][0]

    return (best_chunk_time if best_chunk_time is not None else best_time), confidence


def align_subtitle(
    stream_chunks: list,
    stream_index: dict,
    stream_duration_s: float,
    highlight_chunks: list,
    highlight_duration_s: float,
    highlight_name: str,
) -> list[dict]:
    """
    Slide 30-second windows over the highlight, vote for stream position.
    Returns list of per-window match dicts.
    """
    windows = []
    t = 0.0
    while t < highlight_duration_s - WINDOW_SEC / 2:
        t_end = min(t + WINDOW_SEC, highlight_duration_s)
        hl_text = get_chunks_in_window(highlight_chunks, t, t_end)

        best_pos, conf = vote_stream_position(
            hl_text, stream_index, stream_chunks, stream_duration_s
        )
        if best_pos is not None and conf >= MIN_CONFIDENCE:
            offset = best_pos - t
            windows.append({
                "highlight_start_s": round(t, 1),
                "highlight_end_s": round(t_end, 1),
                "stream_start_s": round(best_pos, 1),
                "stream_end_s": round(best_pos + (t_end - t), 1),
                "offset_s": round(offset, 1),
                "confidence": round(conf, 4),
            })
        t += HOP_SEC

    return windows


# ── Audio fallback: onset strength NCC ───────────────────────────────────────

def _envelope_cache_path(video_path: Path) -> Path:
    return video_path.parent / (video_path.name + ".chatfreq_onset.npy")


def extract_onset_envelope(video_path: Path, force: bool = False) -> tuple[np.ndarray, float]:
    """
    Extract onset strength envelope from a video file using librosa.
    Cached as <video>.chatfreq_onset.npy.
    Returns (envelope_array, hop_duration_s).
    """
    cache = _envelope_cache_path(video_path)
    hop_cache = video_path.parent / (video_path.name + ".chatfreq_onset_hop.txt")
    if cache.exists() and hop_cache.exists() and not force:
        env = np.load(str(cache))
        hop_s = float(hop_cache.read_text().strip())
        print(f"    Loaded cached onset envelope ({len(env)} frames, "
              f"{len(env)*hop_s:.1f}s)  ← {cache.name}")
        return env, hop_s

    import subprocess, io, librosa
    print(f"    Extracting onset envelope: {video_path.name} … ", end="", flush=True)
    t0 = time.time()

    # Extract audio to f32le via FFmpeg pipe
    cmd = [
        "ffmpeg", "-i", str(video_path),
        "-vn", "-ac", "1", "-ar", str(AUDIO_SR),
        "-f", "f32le", "-loglevel", "error",
        "pipe:1",
    ]
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        raise RuntimeError(f"FFmpeg failed: {result.stderr.decode()[:300]}")

    y = np.frombuffer(result.stdout, dtype=np.float32).copy()

    # Compute onset strength (spectral flux) at 512-sample hop (~64ms at 8kHz)
    hop_length = 512
    onset_env = librosa.onset.onset_strength(y=y, sr=AUDIO_SR, hop_length=hop_length)
    hop_s = hop_length / AUDIO_SR

    np.save(str(cache), onset_env)
    hop_cache.write_text(str(hop_s))
    elapsed = time.time() - t0
    print(f"done ({len(onset_env)} frames, {len(onset_env)*hop_s:.1f}s) [{elapsed:.1f}s]")
    return onset_env, hop_s


def pearson_ncc(stream_env: np.ndarray, window: np.ndarray) -> np.ndarray:
    """
    Proper Pearson NCC of window against stream_env.
    Values in [-1, 1].
    """
    from scipy.signal import fftconvolve

    W = len(window)
    N = len(stream_env)
    if W > N:
        return np.array([])

    # Template: zero-mean, unit variance
    t_mean = window.mean()
    t_std = window.std()
    if t_std < 1e-9:
        return np.zeros(N - W + 1)
    t_norm = (window - t_mean) / t_std

    # Numerator: cross-correlation of stream with normalised template
    # result[k] = sum_j t_norm[j] * stream[k+j]
    num = fftconvolve(stream_env, t_norm[::-1], mode="valid") / W

    # Denominator: local std of stream
    ones = np.ones(W)
    slide_sum  = fftconvolve(stream_env,     ones, mode="valid") / W   # local mean
    slide_sum2 = fftconvolve(stream_env**2,  ones, mode="valid") / W   # local E[X^2]
    local_var  = np.maximum(slide_sum2 - slide_sum**2, 0.0)
    local_std  = np.sqrt(local_var)

    denom = np.maximum(local_std, 1e-9)
    return np.clip(num / denom, -1.0, 1.0)


def align_audio_onset(
    stream_video: Path,
    highlight_video: Path,
) -> list[dict]:
    """Onset-strength NCC fallback for highlights without SRT."""
    stream_env, hop_s = extract_onset_envelope(stream_video)
    hl_env, _ = extract_onset_envelope(highlight_video)

    W_frames = int(WINDOW_SEC / hop_s)
    HOP_frames = int(HOP_SEC / hop_s)
    N_stream = len(stream_env)
    N_hl = len(hl_env)

    # Log-compress to reduce dynamic range
    stream_log = np.log1p(stream_env)
    hl_log = np.log1p(hl_env)
    global_std = stream_log.std()

    windows = []
    t_start_f = 0
    while t_start_f + W_frames <= N_hl:
        window = hl_log[t_start_f:t_start_f + W_frames]
        t_h_s = t_start_f * hop_s

        if window.std() < 0.05 * global_std:
            t_start_f += HOP_frames
            continue

        ncc = pearson_ncc(stream_log, window)
        if len(ncc) == 0:
            t_start_f += HOP_frames
            continue

        best_k = int(np.argmax(ncc))
        best_corr = float(ncc[best_k])

        if best_corr >= CORR_THRESHOLD:
            t_s_s = best_k * hop_s
            offset = t_s_s - t_h_s
            windows.append({
                "highlight_start_s": round(t_h_s, 2),
                "highlight_end_s":   round(t_h_s + WINDOW_SEC, 2),
                "stream_start_s":    round(t_s_s, 2),
                "stream_end_s":      round(t_s_s + WINDOW_SEC, 2),
                "offset_s":          round(offset, 2),
                "confidence":        round(best_corr, 4),
            })
        t_start_f += HOP_frames

    return windows


# ── Segment grouping (shared) ─────────────────────────────────────────────────

def group_into_segments(
    windows: list[dict],
    highlight_path: Path,
    method: str,
) -> list[dict]:
    """
    Merge consecutive windows with consistent offsets into alignment segments.
    """
    if not windows:
        return []

    segments = []
    seg = [windows[0]]

    for w in windows[1:]:
        prev = seg[-1]
        same_offset = abs(w["offset_s"] - prev["offset_s"]) <= OFFSET_TOL
        contiguous  = (w["highlight_start_s"] - prev["highlight_end_s"]) <= WINDOW_SEC
        if same_offset and contiguous:
            seg.append(w)
        else:
            if len(seg) >= MIN_SEG_WIN:
                segments.append(seg)
            seg = [w]
    if len(seg) >= MIN_SEG_WIN:
        segments.append(seg)

    result = []
    for idx, seg in enumerate(segments):
        offsets = [w["offset_s"] for w in seg]
        confs   = [w["confidence"] for w in seg]
        median_offset = float(np.median(offsets))

        h_start = seg[0]["highlight_start_s"]
        h_end   = seg[-1]["highlight_end_s"]
        s_start = max(0.0, h_start + median_offset)
        s_end   = h_end + median_offset

        result.append({
            "highlight_file": highlight_path.name,
            "segment_idx": idx + 1,
            "highlight_start_s": round(h_start, 1),
            "highlight_end_s":   round(h_end, 1),
            "stream_start_s":    round(s_start, 1),
            "stream_end_s":      round(s_end, 1),
            "duration_s":        round(h_end - h_start, 1),
            "mean_confidence":   round(float(np.mean(confs)), 4),
            "n_windows":         len(seg),
            "method":            method,
            "highlight_start_hms": seconds_to_hms(h_start),
            "highlight_end_hms":   seconds_to_hms(h_end),
            "stream_start_hms":  seconds_to_hms(s_start),
            "stream_end_hms":    seconds_to_hms(s_end),
        })
    return result


# ── Per-stream orchestration ──────────────────────────────────────────────────

def align_stream(stream_name: str, cfg: dict, force: bool = False):
    print(f"\n{'='*62}")
    print(f"  {stream_name}")
    print(f"{'='*62}")

    out_dir = RESEARCH_DIR / stream_name
    out_dir.mkdir(parents=True, exist_ok=True)

    stream_srt = cfg.get("stream_srt")
    stream_video = cfg["stream_video"]

    # Parse stream subtitle once
    stream_chunks = None
    stream_index = None
    stream_duration_s = None
    if stream_srt and stream_srt.exists():
        print(f"  Parsing stream SRT: {stream_srt.name}")
        stream_chunks = srt_to_timed_words(stream_srt)
        stream_duration_s = stream_chunks[-1][1] if stream_chunks else 0.0
        stream_index = build_stream_ngram_index(stream_chunks, NGRAM_N)
        print(f"    {len(stream_chunks)} chunks  |  {len(stream_index):,} unique {NGRAM_N}-grams  |  "
              f"duration ≈ {seconds_to_hms(stream_duration_s)}")
    else:
        print(f"  WARNING: stream SRT not found: {stream_srt}")

    all_segments = []

    for hl in cfg["highlights"]:
        hl_video = hl["video"]
        hl_srt   = hl.get("srt")

        if not hl_video.exists():
            print(f"\n  WARNING: highlight not found: {hl_video.name}")
            continue

        print(f"\n  Highlight: {hl_video.name[:65]}")

        # ── Subtitle method ──────────────────────────────────────────────────
        if hl_srt is not None and hl_srt.exists() and stream_chunks is not None:
            print(f"  Method: subtitle n-gram alignment")
            hl_chunks = srt_to_timed_words(hl_srt)
            if not hl_chunks:
                print(f"    WARNING: no usable text in highlight SRT; skipping")
                continue
            hl_duration_s = hl_chunks[-1][1]
            print(f"    {len(hl_chunks)} chunks  |  duration ≈ {seconds_to_hms(hl_duration_s)}")

            t0 = time.time()
            windows = align_subtitle(
                stream_chunks, stream_index, stream_duration_s,
                hl_chunks, hl_duration_s, hl_video.name
            )
            elapsed = time.time() - t0
            print(f"    {len(windows)} accepted windows  [{elapsed:.1f}s]")
            method = "subtitle_ngram"

        # ── Audio fallback ───────────────────────────────────────────────────
        else:
            if hl_srt is None:
                print(f"  Method: FALLBACK audio onset NCC (no highlight SRT)")
            else:
                print(f"  Method: FALLBACK audio onset NCC (SRT not found)")
            if not stream_video.exists():
                print(f"    ERROR: stream video not found; skipping")
                continue

            t0 = time.time()
            windows = align_audio_onset(stream_video, hl_video)
            elapsed = time.time() - t0
            print(f"    {len(windows)} accepted windows  [{elapsed:.1f}s]")
            method = "audio_onset"

        segments = group_into_segments(windows, hl_video, method)
        print(f"    → {len(segments)} segments")
        for seg in segments:
            print(f"       seg {seg['segment_idx']:02d}: "
                  f"clip [{seg['highlight_start_hms']} – {seg['highlight_end_hms']}] "
                  f"→ stream [{seg['stream_start_hms']} – {seg['stream_end_hms']}]  "
                  f"conf={seg['mean_confidence']:.3f}  n={seg['n_windows']}")

        all_segments.extend(segments)

    if not all_segments:
        print("  No segments found.")
        return None

    df = pd.DataFrame(all_segments)
    out_path = out_dir / f"{stream_name}_alignment.csv"
    df.to_csv(out_path, index=False)
    print(f"\n  Saved → {out_path.name}  ({len(df)} segments total)")

    print("\n  Per-highlight summary:")
    for hl_name, grp in df.groupby("highlight_file"):
        total = grp["duration_s"].sum()
        print(f"    {hl_name[:60]:60s}: "
              f"{len(grp)} segs, {seconds_to_hms(total)} total")
    return df


def main():
    parser = argparse.ArgumentParser(description="Align highlights to stream")
    parser.add_argument("--stream", default=None, help="Only process this stream name")
    parser.add_argument("--force", action="store_true", help="Re-extract audio even if cached")
    args = parser.parse_args()

    streams_to_run = STREAMS
    if args.stream:
        if args.stream not in STREAMS:
            print(f"Unknown stream '{args.stream}'. Available: {list(STREAMS.keys())}")
            sys.exit(1)
        streams_to_run = {args.stream: STREAMS[args.stream]}

    print("Subtitle / audio alignment — all streams")
    print(f"n-gram: N={NGRAM_N}  window={WINDOW_SEC}s  hop={HOP_SEC}s")
    print(f"min_confidence={MIN_CONFIDENCE}  offset_tol={OFFSET_TOL}s")

    for stream_name, cfg in streams_to_run.items():
        align_stream(stream_name, cfg, args.force)

    print("\n✓ Done.")


if __name__ == "__main__":
    main()
